### ISSUE TITLE
Checkpoint config in mnist example

### ISSUE THREAD

**Issue by lshmouse** [alibaba/x-deeplearning#111]
When runing mnist example in yarn cluster. The xdl scheduler node started failed with following error
```
config: {u'ps': {u'instance_num': 2, u'memory_m': 1000, u'cpu_cores': 2}, u'dependent_dirs': u'/home/liushaohui/workspace/tasks/ali-xdl-demo/mnist', u'script': u'mnist.py', u'worker': {u'instance_num': 5, u'memory_m': 4000, u'cpu_cores': 2}, u'checkpoint': {}, u'max_failover_times': 2, u'job_name': u'xdl_mnist_example', u'docker_image': u'cr.d.xiaomi.net/computing/xdl:ubuntu-cpu-tf1.12'}
Traceback (most recent call last):
  File "mnist.py", line 16, in <module>
    import xdl
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/__init__.py", line 16, in <module>
    from xdl.python.init import *
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/__init__.py", line 16, in <module>
    from xdl.python.init import *
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/init.py", line 42, in <module>
    from xdl.python.training.train_session import TrainSession, LoggerHook, SyncRunHook, SemiSyncRunHook, BarrierHook
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 21, in <module>
    from xdl.python.training.env import current_env, is_local_mode
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 228, in <module>
    _ENV = init_env()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 226, in init_env
    return DistributedEnv()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 127, in __init__
    raise Exception("ckpt_dir is not specified")
Exception: ckpt_dir is not specified
```
How to set checkpint config? is a hdfs path supported?

**Comment by guoxinyang** [comment]
"checkpoint": {
    "output_dir": "hdfs://xxx"
  },

**Comment by lshmouse** [comment]
@guoxinyang Thx. 
Is secure hdfs cluster supported?  Can we set the output dir to a local path to run the example?

**Comment by guoxinyang** [comment]
Yes, use "file://absolute_path" can support local file。But please note that it actually uses file_path in docker.
