### ISSUE TITLE
The mnist example fail

### ISSUE THREAD

**Issue by ronjian** [alibaba/x-deeplearning#14]
First, thanks for the great project.
I tried to run the MNIST example and got some failure. 
```
root@adeb1b227a39:~/x-deeplearning/xdl/examples/mnist# python mnist.py
```
The traceback is as below.
```
Traceback (most recent call last):
  File "mnist.py", line 95, in <module>
    train()
  File "mnist.py", line 51, in train
    train_sess = xdl.TrainSession(hooks=[ckpt_hook])
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 248, in __init__
    self._session = SimpleSession(hooks)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 238, in __init__
    self._session = Session(self._hooks)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 36, in __init__
    self._create_session()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 40, in _create_session
    hook.create_session()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 195, in create_session
    execute_with_retry(variable_registers())
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 159, in execute_with_retry
    return execute(ops)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 35, in check_error
    raise InternalError(status.msg)
xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[Client is not initialized
Check Status [GetClient(&client)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_register_variable_op.cc]Compute@43]
```

**Comment by yiling-dc** [comment]
> First, thanks for the great project.
> I tried to run the MNIST example and got some failure.
> 
> ```
> root@adeb1b227a39:~/x-deeplearning/xdl/examples/mnist# python mnist.py
> ```
> The traceback is as below.
> 
> ```
> Traceback (most recent call last):
>   File "mnist.py", line 95, in <module>
>     train()
>   File "mnist.py", line 51, in train
>     train_sess = xdl.TrainSession(hooks=[ckpt_hook])
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 248, in __init__
>     self._session = SimpleSession(hooks)
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 238, in __init__
>     self._session = Session(self._hooks)
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 36, in __init__
>     self._create_session()
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 40, in _create_session
>     hook.create_session()
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 195, in create_session
>     execute_with_retry(variable_registers())
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 159, in execute_with_retry
>     return execute(ops)
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
>     return current_graph().execute(outputs, run_option, run_statistic)
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
>     check_error(result.status)
>   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 35, in check_error
>     raise InternalError(status.msg)
> xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[Client is not initialized
> Check Status [GetClient(&client)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_register_variable_op.cc]Compute@43]
> ```

If you want to run the example in a local mode, you should add the parameter "--run_mode=local" in your command. Just as the wiki [https://github.com/alibaba/x-deeplearning/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E6%A1%A3#41-%E5%8D%95%E6%9C%BA%E8%AE%AD%E7%BB%83](url)illustrates.

**Comment by lxl910915** [comment]
@yiling-dc  请问有分布式mnist的例子吗？
