### ISSUE TITLE
Crossmedia例子跑不通

### ISSUE THREAD

**Issue by bboy-yang** [alibaba/x-deeplearning#163]
按照xdl的CrossMedia样例，分布式运行。已经解决1：data.txt数据与runner对应不起来；2：config的文件缺少checkpoint路径。然而运行还是报错：
Traceback (most recent call last):
  File "runner.py", line 150, in <module>
    run()
  File "runner.py", line 146, in run
    values = sess.run(run_ops)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 266, in run
    return self._session.run(v, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 241, in run
    return self._session.run(v, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 49, in run
    results = execute(run_item, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 35, in check_error
    raise InternalError(status.msg)
xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[tf session run failed, errormsg:segment ids must be < num_segments
         [[{{node SparseSegmentSumWithNumSegments}} = SparseSegmentSumWithNumSegments[T=DT_FLOAT, Tidx=DT_INT32, Tnumsegments=DT_INT32, _output_shapes=[<unknown>], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_5_0_5, range, _arg_Placeholder_3_0_3, strided_slice_1)]]
Check Status [tf_runner_.Run(tf_inputs, output_op_names, &results)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/backend/tf/backend_op.cc]Compute@90]

**Comment by bboy-yang** [comment]
已得到解决：原因在于runner中的这个函数有问题，改成如下形式正常运行。
def to_tf_segment_id(seg):
  l = []
  segx = seg.tolist()
  z = 0
  e = 0
  for i in range(len(segx)):
    l += [e for j in range(z, segx[i])]
    z = segx[i]
    e = e + 1
  return np.array(l, np.int32)
