### ISSUE TITLE
分布式任务，ps启动时报segmentation falt

### ISSUE THREAD

**Issue by simon1024** [alibaba/x-deeplearning#180]
在起分布式任务的时候，ps总是报setmentation falt。
集群规模如下：
ps：8
worker：32

ps报错信息：
<pre>
2019-03-17 16:45:04,266:106(0x7f04ec3ff700):ZOO_INFO@check_events@2454: initiated connection to server xxxx:2181
2019-03-17 16:45:04,268:106(0x7f04ec3ff700):ZOO_INFO@check_events@2506: session establishment complete on server xxxx:2181, sessionId=0x1011a69ab870025, negotiated timeout=4000 
Segmentation fault on shard 0.
Backtrace:
  0x000000000084619c
  0x00000000008462c0
  0x0000000000846335
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  0x00000000007bd2c5
  0x00000000008c32c6
  0x00000000008c3b82
  0x000000000083dc0c
  0x000000000083dc2b
  0x0000000000896d12
  0x000000000091665a
  0x00000000007e41b6
  0x00000000007dd772
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x00000000000b8c7f
  /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c
Segmentation fault
cmd: /usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/utils/../../bin/ps -bc "False" -sp "zfs://xxxx:2181" -si "1" -r "server"
Traceback (most recent call last):
    ……
    import xdl
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/__init__.py", line 16, in &lt;module&gt;
    from xdl.python.init import *
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/__init__.py", line 16, in &lt;module&gt;
    from xdl.python.init import *
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/init.py", line 42, in &lt;module&gt;
    from xdl.python.training.train_session import TrainSession, LoggerHook, SyncRunHook, SemiSyncRunHook, BarrierHook
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 21, in &lt;module&gt;
    from xdl.python.training.env import current_env, is_local_mode
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 228, in &lt;module&gt;
    _ENV = init_env()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 226, in init_env
    return DistributedEnv()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 148, in __init__
    self._start()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 54, in _start
    self._ps_do()
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/env.py", line 157, in _ps_do
    bind_cores = self._bind_core)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/utils/ps_utils.py", line 78, in run_ps_server
    bc=bind_cores)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/utils/ps_utils.py", line 67, in run_ps_cmd
    raise ValueError("Run cmd Error, cmd=[%s] exit_code=[%s]" % (cmd, ret))
ValueError: Run cmd Error, cmd=[/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/utils/../../bin/ps -bc "False" -sp "zfs://10.105.136.134:2181" -si "1" -r "server"] exit_code=[35584]
</pre>

看到之前也有人提过这个问题，但是没有回复，所以这里重开issue提下。

**Comment by lovickie** [comment]
可以把coredump的栈信息打印一下么？一般可能是在/home/admin/coredump或者/home/coredump里

**Comment by simon1024** [comment]
> 可以把coredump的栈信息打印一下么？一般可能是在/home/admin/coredump或者/home/coredump里

我用kubeflow跑的，core之后pod就退出了，我看看有没办法拿到信息

**Comment by simon1024** [comment]
> 可以把coredump的栈信息打印一下么？一般可能是在/home/admin/coredump或者/home/coredump里

重新复现了下问题，看ps-plus.INFO日志如下：
<pre>
Log file created at: 2019/03/18 17:09:36
Running on machine: pi-v5-xdl-wendao-3-6d0147-ps-0
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0318 17:09:36.691653   212 server_service.cc:325] Cannot Get Scheduler Addr[zfs://10.108.74.29:2181]: Store[]
</pre>
跟到对应代码如下：
<pre>
void ServerService::RegisterServer() {
  std::string old_scheduler_addr;
  while (!stop_) {
    std::this_thread::sleep_for(std::chrono::seconds(10));
    std::string scheduler_addr;
    Status st = ReliableKV::ReadAny(scheduler_kv_addr_, &scheduler_addr);
    if (!st.IsOk()) {
      LOG(WARNING) << "Cannot Get Scheduler Addr[" << scheduler_kv_addr_ << "]: Status[" << st.ToString();
      continue;
    }   

    size_t pos = scheduler_addr.find('^');
    if (pos == std::string::npos) {
      LOG(WARNING) << "Cannot Get Scheduler Addr[" << scheduler_kv_addr_ <<  
        "]: Store[" << scheduler_addr << "]";
    }

    scheduler_addr = scheduler_addr.substr(pos + 1); 
    if (scheduler_addr != old_scheduler_addr) {
      seastar_lib_->Connect(0, scheduler_addr);
      old_scheduler_addr = scheduler_addr;                                                                                                                                  
    }

    std::promise<Status> result;
    std::vector<Data*> request_datas = { 
      new WrapperData<ps::ServerInfo>(0, server_id_, server_version_, ip_, port_)
    };  
    seastar_lib_->Request(0, func_ids::kSchedulerRegisterServer, request_datas,
        new ps::service::seastar::CallBackClosure([&result](const SeastarStatus& sst, const std::vector<ps::Data*>& datas) {
          if (!sst.Success()) {
            LOG(ERROR) << "register server failed, error: " << sst.ToString();
            result.set_value(Status::NetworkError("Scheduler Error"));
          } else {
            LOG(INFO) << "register server result: " << GetNetworkStatus(datas).ToString();
            result.set_value(GetNetworkStatus(datas));
          }   
    }));
    result.get_future().wait();
  }
}
</pre>
