### ISSUE TITLE
自行编译XDL，DIEN单机训练无法运行

### ISSUE THREAD

**Issue by wangzhimingchn** [alibaba/x-deeplearning#196]
x-deeplearning/xdl-algorithm-solution/DIEN/script/ 实例无法运行，提示错误如下：
# python train.py --run_mode=local --config=config.json
config: {u'checkpoint': {u'save_interval': 20000, u'output_dir': u'./ckpt_dir/'}, u'job_type': u'train', u'model': u'dien', u'seed': 3, u'data_dir': u'../data'}
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    train()
  File "train.py", line 71, in train
    train_ops = model.build_final_net(EMBEDDING_DIM, sample_io)
  File "/root/x-deeplearning/xdl-algorithm-solution/DIEN/script/model.py", line 291, in build_final_net
    *self.xdl_embedding(datas, EMBEDDING_DIM, *sample_io.get_n()))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/backend/tf/tf_backend.py", line 160, in _wrapper
    input = recursive_make_placeholder(x, xdl_inputs, placeholders)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/backend/tf/tf_backend.py", line 49, in recursive_make_placeholder
    placeholder = make_placeholder(x)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/backend/tf/tf_backend.py", line 76, in make_placeholder
    if len(x.shape) > 1:
TypeError: object of type 'NoneType' has no len()

**Comment by songyue1104** [comment]
已经修复，请重新编译
