### ISSUE TITLE
分布式xdl训练hdfs报错

### ISSUE THREAD

**Issue by UanonymousU** [alibaba/x-deeplearning#202]
save checkpoint at global_step[20], ckpt version[ckpt-..................20]
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    train(is_training=True)
  File "train.py", line 277, in train
    result = sess.run([train_op, xdl.get_collection(xdl.UPDATE_OPS)])
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 266, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 241, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 55, in run
    cbs[i](results[i + 1])
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 161, in after_run
    self._saver.save(version)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 87, in save
    execute(self.save_op(version))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 305, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 35, in check_error
    raise InternalError(status.msg)
xdl.python.lib.error.InternalError: ErrorCode[3], ErrorMsg[Create Hdfs Error hdfs:///user/tdm_mock_init/checkpoint/ckpt-..................20/__meta__
Check Status [PS2XDL::ConvertStatus(st)] at [/work/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]

@songyue1104

**Comment by yiling-dc** [comment]
官方提供的镜像里是没有HDFS环境的，请确认一下在启动之前有没有在镜像中补充安装HDFS环境

**Comment by githcx** [comment]
保存ckpt的目录有误，没有填写ip、port信息，导致hdfs连接不成功

在配置文件中（config.train.json）修改checkpoint output_dir为以下格式

>   "checkpoint": {
>     "output_dir": "hdfs://namenode_ip:namenode_port/path/to/your/hdfs/checkpoint/root/dir"
>   },

**Comment by UanonymousU** [comment]
thx @yiling-dc @githcx
