### ISSUE TITLE
tdm tdm_ub_att_ubuntu train error

### ISSUE THREAD

**Issue by better629** [alibaba/x-deeplearning#250]
I built the XDL and the *.json files follows the instruction `https://github.com/alibaba/x-deeplearning/wiki/%E6%B7%B1%E5%BA%A6%E6%A0%91%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%9E%8B(TDM)`
But When I run `python train.py --run_mode=local --config=config.train.json`, the error was  
```
if mx.symbol.FullyConnected
[WARNING]: no gradient found for var:bn_1_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_1_d_moving_var under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_2_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_2_d_moving_var under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_3_d_moving_mean under scope: , maybe not used?
[WARNING]: no gradient found for var:bn_3_d_moving_var under scope: , maybe not used?
>>>>>>>>>>>> 0 >>>>>>>>>>>
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    train(is_training=True)
  File "train.py", line 274, in train
    result = sess.run([train_op, xdl.get_collection(xdl.UPDATE_OPS)])
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 268, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 241, in run
    return self._session.run(v, run_option, run_statistic, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 54, in run
    results = execute(run_item, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 305, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 177, in execute
    result = pybind.execute(self._graph_def, xdl_output_spec, run_option)
RuntimeError: [01:57:37] /usr/local/lib/python2.7/dist-packages/mxnet/cpp-package/include/mxnet-cpp/symbol.hpp:
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
Exception AttributeError: "'NoneType' object has no attribute 'NNSymbolFree'" in <object repr() failed> ignored
```
The mock.dat is the file in the repo.

**Comment by better629** [comment]
@songyue1104 please have a look.

**Comment by songyue1104** [comment]
my colleague will check this later

**Comment by better629** [comment]
The above was caused by mxnet version(I used mxnet=1.3.x branch(version=1.3.1)). But when i change to mxnet=1.3.0, and clean the environment, then build the xdl again. 
The output of `python train.py --run_mode=local --config=config.train.json` is
```
Traceback (most recent call last):
  File "train.py", line 386, in <module>
    train(is_training=True)
  File "train.py", line 228, in train
    re = dnn_model_define(emb, batch["indicators"][0], unit_id_expand_emb, batch["label"], data_io._batch_size, emb_dim, 600, '20,20,10,10,2,2,2,1,1,1')
  File "/usr/local/lib/python2.7/dist-packages/xdl/python/backend/mxnet/mxnet_backend.py", line 249, in _wrapper
    model_outputs = model_func(*placeholders, **kwargs)
  File "train.py", line 167, in dnn_model_define
    user_input_before_reshape = mx.sym.concat(*user_input)
  File "<string>", line 86, in concat
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.3.0-py2.7.egg/mxnet/_ctypes/symbol.py", line 125, in _symbol_creator
    ctypes.byref(sym_handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-1.3.0-py2.7.egg/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for num_args expect int but value='69', in operator Concat(name="", num_args="69")
```

It seems that is the ` mx.sym.concat` problem. But the execution of `python estimator_mxnet_test.py --run_mode=local --ckpt_dir=./ckpt --task_type=train` which is a example in xdl is fine. The output is 
```
lstep[100] gstep[99] lqps[301.6] gqps[301.6] auc[0.0]
lstep[200] gstep[199] lqps[301.6] gqps[301.6] auc[0.0]
....
```

**Comment by lovickie** [comment]
Did you use registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-mxnet1.3 or install mxnet yourself? In registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-gpu-mxnet1.3, we have installed mxnet, and the TDM example can be run well.

**Comment by lovickie** [comment]
user_input is an array, length=69,   mx.sym.concat(*user_input)  means concat 69 inputs, which called mxnet op Concat(name="", num_args=69), but I don't know why it changed to Concat(name="", num_args="69"). Check the Concat op in the mxnet you installed?

**Comment by better629** [comment]
@lovickie

**Comment by better629** [comment]
> user_input is an array, length=69, mx.sym.concat(*user_input) means concat 69 inputs, which called mxnet op Concat(name="", num_args=69), but I don't know why it changed to Concat(name="", num_args="69"). Check the Concat op in the mxnet you installed?

@lovickie 
I know the parameter num_args is `int` type, which is also ok in example `python estimator_mxnet_test.py` with `mxnet.sym.concat`. But failed in `TDM/script/tdm_ub_att_ubuntu/train.py`.

**Comment by better629** [comment]
@lovickie @woso 
The `tdm_ub_att_ubuntu` example in the docker `registry.cn-hangzhou.aliyuncs.com/xdl/xdl:ubuntu-cpu-mxnet1.3` can only work with official-build xdl(version=1.0 tag=v1.1), but not work with user-build xdl(version=1.2) in cpu docker.
The versin=1.0 xdl can't use `import xdl.python.training.export` to export model. And the blaze proto version problem has not fixed yet.

It's really not easy to use such a open-project that can only be used in official particular version.
