### ISSUE TITLE
读hdfs crash

### ISSUE THREAD

**Issue by codescv** [alibaba/x-deeplearning#33]
运行命令: python deepctr.py --run_mode=local
文件路径：hdfs://some-server/aaa/bbb.txt

环境变量: 设置了HADOOP_HOME, PATH等，hdfs命令可以列出文件。

core:

```
#0  std::function<hdfs_internal* (char const*, unsigned short)>::operator()(char const*, unsigned short) const (__args#1=0,
    __args#0=0x1c20f48 "some-server", this=0x70) at /

**Comment by songyue1104** [comment]
HADOOP_HDFS_HOME这个环境变量设了吗？

**Comment by codescv** [comment]
HADOOP_HOME=/usr/hdp/2.6.1.0-129/hadoop
HADOOP_HDFS_HOME=/usr/hdp/2.6.1.0-129/hadoop-hdfs

$HADOOP_HDFS_HOME/bin/hdfs dfs -ls 可以显示样本文件
还缺什么吗？

样本路径应该如何设置？
我试过:  
hdfs:/path/to/file
hdfs://server/path/to/file
hdfs:///path/to/file
hdfs://default/path/to/file

都会core

**Comment by codescv** [comment]
export HADOOP_HDFS_HOME=/usr/hdp/2.6.1.0-129/hadoop
ls $HADOOP_HDFS_HOME/lib/native/libhdfs.so
/usr/hdp/2.6.1.0-129/hadoop/lib/native/libhdfs.so

这个文件是有的, 仍然和之前一样的错误

对hadoop版本有要求吗？

**Comment by guoxinyang** [comment]
你尝试把 namenode指定为 xxx-host:9000 而不是 yiran-data-ns

**Comment by githcx** [comment]
> yiran

我觉得是时候把我的错误贴上来了，做TDM的训练的部分，跑下面这句，也是一样的问题：
python train.py --run_mode=local --config=config.train.json

可以考虑在镜像里加上配好的hadoop，如果这个问题是hadoop配置引起的话

> #0  0x00007fffcaba98ce in std::function<hdfs_internal* (char const*, unsigned short)>::operator()(char const*, unsigned short) const (__args#1=0, 
    __args#0=0x23df6f8 "http://localhost:9000", this=0x7fffcb5b49b8) at /usr/include/c++/5/functional:2267
#1  xdl::io::FileSystemHdfs::FileSystemHdfs (this=0x9b8a20, namenode=0x1cb28a8 "http://localhost:9000") at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:222
#2  0x00007fffcaba9af8 in xdl::io::FileSystemHdfs::Get (namenode=0x1cb28a8 "http://localhost:9000") at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:212
#3  0x00007fffcaba7a9b in xdl::io::GetFileSystem (type=type@entry=xdl::io::kHdfs, ext=<optimized out>) at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system.cc:58
#4  0x00007fffcab8d05b in xdl::io::DataIO::DataIO (this=0x9b8ce0, ds_name="tdm", parser_type=<optimized out>, fs_type=xdl::io::kHdfs, namenode="http://localhost:9000")
    at /home/yue.song/x-deeplearning/xdl/xdl/data_io/data_io.cc:31

**Comment by sydpz** [comment]
我最近也遇到类似的问题，

**Comment by githcx** [comment]
> > yiran
> 
> 我觉得是时候把我的错误贴上来了，做TDM的训练的部分，跑下面这句，也是一样的问题：
> python train.py --run_mode=local --config=config.train.json
> 
> 可以考虑在镜像里加上配好的hadoop，如果这个问题是hadoop配置引起的话
> 
> > #0  0x00007fffcaba98ce in std::function<hdfs_internal* (char const*, unsigned short)>::operator()(char const*, unsigned short) const (__args#1=0,
> > __args#0=0x23df6f8 "http://localhost:9000", this=0x7fffcb5b49b8) at /usr/include/c++/5/functional:2267
> > #1  xdl::io::FileSystemHdfs::FileSystemHdfs (this=0x9b8a20, namenode=0x1cb28a8 "http://localhost:9000") at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:222
> > #2  0x00007fffcaba9af8 in xdl::io::FileSystemHdfs::Get (namenode=0x1cb28a8 "http://localhost:9000") at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system_hdfs.cc:212
> > #3  0x00007fffcaba7a9b in xdl::io::GetFileSystem (type=type@entry=xdl::io::kHdfs, ext=) at /home/yue.song/x-deeplearning/xdl/xdl/data_io/fs/file_system.cc:58
> > #4  0x00007fffcab8d05b in xdl::io::DataIO::DataIO (this=0x9b8ce0, ds_name="tdm", parser_type=, fs_type=xdl::io::kHdfs, namenode="http://localhost:9000")
> > at /home/yue.song/x-deeplearning/xdl/xdl/data_io/data_io.cc:31

反过头来看，当初看下源码的libhdfs.cc文件的以下段落，就不会卡在这个地方了。
这个应该补充到用户文档，毕竟是很关键的hadoop的环境配置。使用者要求debug到代码里，对于初学初次使用门槛略高。
![image](https://user-images.githubusercontent.com/2312126/55532982-5fb7f600-56e2-11e9-8384-3840a09cce98.png)

**Comment by ustcdane** [comment]
同样遇到HDFS 出现 CORE，但是和上面各位不同，这次主要是安全认证问题，错误如下，分享下解决办法：
如果 不存在 /etc/krb5.conf 文件，则找到这个文件 拷贝到etc目录下:
cp /home/xxx/conf/krb5.conf   /etc/



Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:84)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
	... 7 more
Caused by: KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
	... 13 more
2019-08-20 02:26:42.982400: F /home/yue.song/XDL-OpenSource-master/xdl/xdl/data_io/fs/file_system_hdfs.cc:223] Check failed: fs_ != nullptr Failed to load HDFS-configuration:hdfs://10.140.48.106:9000
Aborted (core dumped)

**Comment by ustcdane** [comment]
遇到如下的问题

Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:413)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:731)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:727)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1865)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 22 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
	... 31 more
2019-08-20 08:04:43.609134: F /home/yue.song/XDL-OpenSource-master/xdl/xdl/data_io/fs/file_system_hdfs.cc:129] Check failed: info != nullptr can't open dir hdfs://10.140.52.62:8020/user/iminers/wangdan/tdm_t/tree_data/data
