### ISSUE TITLE
分布式提交yarn.io/gpu报错

### ISSUE THREAD

**Issue by niumeng07** [alibaba/x-deeplearning#42]
org.apache.hadoop.yarn.exceptions.ResourceNotFoundException: Unknown resource 'yarn.io/gpu'. Known resources are [name: memory-mb, units: Mi, type: COUNTABLE, value: 15360, minimum allocation: 0, maximum allocation: 9223372036854775807, name: vcores, units: , type: COUNTABLE, value: 8, minimum allocation: 0, maximum allocation: 9223372036854775807]
	at org.apache.hadoop.yarn.api.records.Resource.getResourceInformation(Resource.java:269)
	at org.apache.hadoop.yarn.api.records.impl.pb.ResourcePBImpl.getResourceInformation(ResourcePBImpl.java:208)
	at org.apache.hadoop.yarn.api.records.Resource.getResourceValue(Resource.java:306)
	at org.apache.hadoop.yarn.api.records.impl.pb.ResourcePBImpl.getResourceValue(ResourcePBImpl.java:214)
	at com.alibaba.xdl.AppMasterBase.initResource(AppMasterBase.java:831)
	at com.alibaba.xdl.AppMasterBase.run(AppMasterBase.java:161)
	at com.alibaba.xdl.AppMasterRunner.main(AppMasterRunner.java:87)

在config.json配置中已经设置了"gpu_cores": 0。
首先是不打算用GPU的。
所以我的问题是，这个参数是集群配置？还是提交代码的时候有额外的配置。
另外，我看在yarn_patch文件下，有关于GPU的JAR包，这部分怎么使用？

**Comment by niumeng07** [comment]
> @niumeng07 请问你的yarn版本是3.1.0以后的版本？

感谢回复，版本是3.1.0，目前这个问题已经解决了，需要在集群的xml配置里加入这个项。
