### ISSUE TITLE
分布式训练 hadoop

### ISSUE THREAD

**Issue by jingcheng-WU** [alibaba/x-deeplearning#54]
请问分布式训练的hadoop是安装在宿主机上还是docker内进行安装啊？
安装好hadoop的集群上进行分布式训练报错如下：
java.lang.IllegalArgumentException: Wrong FS: hdfs://172.16.7.225:4007user/root/.xdl/application_1546239999977_0006, expected: hdfs://172.16.7.225:4007
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:649)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
	at com.alibaba.xdl.Utils.genAppBasePath(Utils.java:58)
	at com.alibaba.xdl.Client.run(Client.java:116)
	at com.alibaba.xdl.Client.main(Client.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException: Application with id 'application_1546239999977_0006' doesn't exist in RM.
	at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getApplicationReport(ClientRMService.java:327)
	at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getApplicationReport(ApplicationClientProtocolPBServiceImpl.java:175)
	at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:417)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2045)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
	at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:101)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getApplicationReport(ApplicationClientProtocolPBClientImpl.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy8.getApplicationReport(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getApplicationReport(YarnClientImpl.java:430)
	at com.alibaba.xdl.Client.dealWithInterruption(Client.java:303)
	at com.alibaba.xdl.Client$1.run(Client.java:347)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException): Application with id 'application_1546239999977_0006' doesn't exist in RM.
	at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getApplicationReport(ClientRMService.java:327)
	at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getApplicationReport(ApplicationClientProtocolPBServiceImpl.java:175)
	at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:417)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2045)

	at org.apache.hadoop.ipc.Client.call(Client.java:1475)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy7.getApplicationReport(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getApplicationReport(ApplicationClientProtocolPBClientImpl.java:191)

**Comment by lxl910915** [comment]
@jingcheng-WU 
hdfs://172.16.7.225:4007user/root/.xdl/application_1546239999977_0006
这一行在4007后面少了一个“/”，看下Utils类中genAppBasePath方法把"/"去掉了
![image](https://user-images.githubusercontent.com/8842010/51456832-0a7a7280-1d8a-11e9-9177-4e34ed69f231.png)

**Comment by woisnow** [comment]
+1

**Comment by UanonymousU** [comment]
请问解决了么，我们训练也是这个问题@jingcheng-WU

**Comment by UanonymousU** [comment]
> 请问解决了么，我们训练也是这个问题@jingcheng-WU

@songyue1104 @lxl910915 @woisnow @jingcheng-WU

**Comment by githcx** [comment]
> 在docker内部安装，并且需要在/etc/profile里设置相关环境变量
> export HADOOP_HOME=/path/to/hadoop
> export HADOOP_HDFS_HOME=$HADOOP_HOME
> export HADOOP_CLASSPATH=$(find $HADOOP_HOME -name '*.jar' | xargs echo | tr ' ' ':')
> export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
> export PATH=$PATH:$HADOOP_HOME/bin
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib/amd64/server/:/usr/local/nvidia/lib64/
> export CLASSPATH=$CLASSPATH:$HADOOP_CLASSPATH

hadoop 的 hdfs服务应该配置在宿主机，包括namenode和datanode等，docker内部仅仅按照 @songyue1104 的解答配置客户端正常运行需要的环境变量信息。

**Comment by mengyiliu22** [comment]
> > 在docker内部安装，并且需要在/etc/profile里设置相关环境变量
> > export HADOOP_HOME=/path/to/hadoop
> > export HADOOP_HDFS_HOME=$HADOOP_HOME
> > export HADOOP_CLASSPATH=$(find $HADOOP_HOME -name '*.jar' | xargs echo | tr ' ' ':')
> > export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
> > export PATH=$PATH:$HADOOP_HOME/bin
> > export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib/amd64/server/:/usr/local/nvidia/lib64/
> > export CLASSPATH=$CLASSPATH:$HADOOP_CLASSPATH
> 
> hadoop 的 hdfs服务应该配置在宿主机，包括namenode和datanode等，docker内部仅仅按照 @songyue1104 的解答配置客户端正常运行需要的环境变量信息。

请问组集群的机器上要配置docker和xdl吗

**Comment by mengyiliu22** [comment]
在core-site文件里，使fs.defaultFS的value以/结尾可以解决
