### ISSUE TITLE
调用Save报错

### ISSUE THREAD

**Issue by niumeng07** [alibaba/x-deeplearning#56]
调用Save保存到Hdfs报错，请问原因是什么，报错内容为：
Traceback (most recent call last):
  File "deepctr.py", line 74, in <module>
    train()
  File "deepctr.py", line 54, in train
    saver.save(version = checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 79, in save
    execute(self.save_op(version))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 33, in check_error
    raise PsError(status.msg)
xdl.python.lib.error.PsError: ErrorCode[4], ErrorMsg[The current op is to save checkpoint `10000`, not assigning new op to save checkpoint `10000`
Check Status [PS2XDL::ConvertStatus(st)] at [/tmp/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]
2019-01-09 08:42:02,401:7(0x7fd637b82700):ZOO_INFO@zookeeper_close@3222: Closing zookeeper sessionId=0x2666712ffee11c0 to 172.31.39.58:2181

**Comment by songyue1104** [comment]
只在worker0上添加CheckpointHook

**Comment by bcfntu** [comment]
if int(xdl.get_task_index()) == 0:
    saver = xdl.Saver()
    checkpoint_version = "001"
    saver.save(version = checkpoint_version)
@songyue1104 
直接这么写，但是报错：
Traceback (most recent call last):
  File "deepctr.py", line 101, in <module>
    run_train(train_path)
  File "deepctr.py", line 74, in run_train
    saver.save(version = checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/saver.py", line 85, in save
    execute(self.save_op(version))
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 33, in check_error
    raise PsError(status.msg)
xdl.python.lib.error.PsError: ErrorCode[4], ErrorMsg[The current op is to save checkpoint `001`, not assigning new op to save checkpoint `001`
Check Status [PS2XDL::ConvertStatus(st)] at [/data/allenbian/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_save_op.cc]operator()@40]
