### ISSUE TITLE
尝试跑TDM tree_init.py代码出错

### ISSUE THREAD

**Issue by zhengkai215** [alibaba/x-deeplearning#60]
运行`python tree_init.py`时报错：
`Traceback (most recent call last):
  File "tree_init.py", line 25, in <module>
    from cluster import Generator
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/cluster/__init__.py", line 18, in <module>
    from .generator import Generator
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/cluster/generator.py", line 31, in <module>
    import tree_builder
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/cluster/tree_builder.py", line 29, in <module>
    from store import KVItem
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/store/__init__.py", line 20, in <module>
    from .store import Store
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/store/store.py", line 18, in <module>
    from .store_api import *
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/store/store_api.py", line 41, in <module>
    _store_api = swig_import_helper()
  File "/your/path/work/tdm_mock/tdm_ub_att_ubuntu/store/store_api.py", line 37, in swig_import_helper
    _mod = imp.load_module('_store_api', fp, pathname, description)
ImportError: libdist_tree.so: cannot open shared object file: No such file or directory`

提示无法找到libdist_tree.so，但/your/path/work/tdm_mock/tdm_ub_att_ubuntu和store目录下均包含了libdist_tree.so文件。
望解答，谢谢。

**Comment by zhuiyuan616124** [comment]
把libdist_tree.so的路径放到/etc/ld.so.conf 文件里，然后执行ldconfig

**Comment by zhengkai215** [comment]
> 把libdist_tree.so的路径放到/etc/ld.so.conf 文件里，然后执行ldconfig

谢谢 可以了！
