### ISSUE TITLE
分布式场景下怎么做barrier

### ISSUE THREAD

**Issue by jeff05** [alibaba/x-deeplearning#77]
手动方式启动分布式训练，scheduler，2个ps都正常启动了，worker用xdl.execute(xdl.worker_barrier_op(np.array(xdl.get_task_index(), dtype=np.int32), np.array(xdl.get_task_num(), dtype=np.int32)))进行barrier同步，执行报错

train代码如下
-----------------
`for i in range(epoch_num):
    xdl.execute(xdl.worker_barrier_op(np.array(xdl.get_task_index(), dtype=np.int32), np.array(xdl.get_task_num(), dtype=np.int32)))
    _epoch = i
    train()
    evaluate()
`

启动worker报错
----------
2019-01-21 14:38:53,696:24629(0x7f4435754700):ZOO_INFO@check_events@2454: initiated connection to server 172.27.128.61:9091
2019-01-21 14:38:53,704:24629(0x7f4435754700):ZOO_INFO@check_events@2506: session establishment complete on server 172.27.128.61:9091, sessionId=0x166f883a9d73db7, negotiated timeout=4000
Disconnected By read zero
Traceback (most recent call last):
  File "deepctr_test.py", line 207, in <module>
    xdl.execute(xdl.worker_barrier_op(np.array(xdl.get_task_index(), dtype=np.int32), np.array(xdl.get_task_num(), dtype=np.int32)))
  File "/home/debug/pico-competive/xdl-work/xdl/site-packages/xdl/python/lib/graph.py", line 242, in execute
    return current_graph().execute(outputs, run_option, run_statistic)
  File "/home/debug/pico-competive/xdl-work/xdl/site-packages/xdl/python/lib/graph.py", line 178, in execute
    check_error(result.status)
  File "/home/debug/pico-competive/xdl-work/xdl/site-packages/xdl/python/lib/error.py", line 33, in check_error
    raise PsError(status.msg)
xdl.python.lib.error.PsError: ErrorCode[4], ErrorMsg[network error
Check Status [PS2XDL::ConvertStatus(st)] at [/root/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_synchronizer_ops.cc]operator()@123]
2019-01-21 14:38:54,803:24629(0x7f44990fd740):ZOO_INFO@zookeeper_close@3222: Closing zookeeper sessionId=0x166f883a9d73db7 to xxx.xxx.xxx.xxx:9091

scheduler日志
------------
server read exception: bad_function_call, errno: 1
WARN  2019-01-21 14:33:46,236 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-01-21 14:33:46,296 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Established connection: server_id =   0 on cpu   0, server addr: xxx.xxx.xxx.xxx:35015.
Established connection: server_id =   1 on cpu   1, server addr: xxx.xxx.xxx.xxx::33074.
server read exception: bad_function_call, errno: 1

ps日志
------------
2019-01-21 14:35:25,911:24473(0x7fc0c93ea700):ZOO_INFO@check_events@2506: session establishment complete on server 172.27.128.61:9091, sessionId=0x166f883a9d73db4, negotiated timeout=4000
,948 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-01-21 14:35:13,949 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-01-21 14:35:13,950 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-01-21 14:35:13,950 seastar - Seastar compiled with default allocator, heap profiler not supported
WARN  2019-01-21 14:35:14,011 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Established connection: server_id =   0 on cpu   0, server addr: xxx.xxx.xxx.xxx:51256.
server read end: client close the connection

**Comment by guoxinyang** [comment]
这个报错是network error，感觉是client和scheduler通信问题？如果先关掉barrier的话，训练正常吗？

**Comment by jeff05** [comment]
嗯，关掉barrier正常训练。
但是，关掉barrier变成两个worker独立训练自己那块数据。
现在是想跑分布式的sync（每个bach间barrier）和async（没各epoch间barrier），请问该怎么写barrier呢
