### ISSUE TITLE
[bug] 跑分布式任务时出错，local 模式下没问题

### ISSUE THREAD

**Issue by sosofun** [alibaba/x-deeplearning#98]
分布式环境没问题，用分布式跑通了官方mnist 和 deepctr 示例；
在更改自己真实模型时遇到问题， 求助！报错信息如下：

`2019-01-25T09:30:24.7554012Z Traceback (most recent call last):
2019-01-25T09:30:24.755429401Z data parallel for file:  ./hdfs/part-00369-000
2019-01-25T09:30:24.755447026Z ('data paths:', ['./hdfs/part-00369-000'])
2019-01-25T09:30:24.755429957Z   File "run_distribute.py", line 228, in <module>
2019-01-25T09:30:24.755456247Z     train()
2019-01-25T09:30:24.755458994Z   File "run_distribute.py", line 126, in train
2019-01-25T09:30:24.755470179Z     train_sess = xdl.TrainSession()
2019-01-25T09:30:24.755483806Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 248, in __init__
2019-01-25T09:30:24.755487524Z     self._session = SimpleSession(hooks)
2019-01-25T09:30:24.75549073Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 238, in __init__
2019-01-25T09:30:24.755498692Z     self._session = Session(self._hooks)
2019-01-25T09:30:24.755501845Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 36, in __init__
2019-01-25T09:30:24.755508594Z     self._create_session()
2019-01-25T09:30:24.755511517Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/framework/session.py", line 40, in _create_session
2019-01-25T09:30:24.755528759Z     hook.create_session()
2019-01-25T09:30:24.755531992Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 196, in create_session
2019-01-25T09:30:24.755545469Z     execute_with_retry(global_initializers())
2019-01-25T09:30:24.755551913Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/training/train_session.py", line 159, in execute_with_retry
2019-01-25T09:30:24.75556687Z     return execute(ops)
2019-01-25T09:30:24.755571609Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 242, in execute
2019-01-25T09:30:24.755599181Z     return current_graph().execute(outputs, run_option, run_statistic)
2019-01-25T09:30:24.755603925Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/graph.py", line 178, in execute
2019-01-25T09:30:24.755622889Z     check_error(result.status)
2019-01-25T09:30:24.755627597Z   File "/usr/local/lib/python2.7/dist-packages/xdl-1.0-py2.7.egg/xdl/python/lib/error.py", line 29, in check_error
2019-01-25T09:30:24.755631354Z     raise ArgumentError(status.msg)
2019-01-25T09:30:24.755676235Z xdl.python.lib.error.ArgumentError: ErrorCode[1], ErrorMsg[Cannot Placement, Too Heavy
2019-01-25T09:30:24.75568184Z Check Status [PS2XDL::ConvertStatus(st)] at [/home/yue.song/x-deeplearning/xdl/xdl/core/ops/ps_ops/ps_truncated_normal_initializer_op.cc]operator()@48]`

**Comment by yiling-dc** [comment]
ps的内存不够，在配置文件XXX.json里面增加ps的个数，或者增加单个ps的内存。

**Comment by sosofun** [comment]
> ps的内存不够，在配置文件XXX.json里面增加ps的个数，或者增加单个ps的内存。

不应该啊， 同样的数据，local就没有问题， 改分布式1ps /1 worker,  把ps 内存从48G增加到128G，还是 worker 报这个错误...

**Comment by yiling-dc** [comment]
> > ps的内存不够，在配置文件XXX.json里面增加ps的个数，或者增加单个ps的内存。
> 
> 不应该啊， 同样的数据，local就没有问题， 改分布式1ps /1 worker, 把ps 内存从48G增加到128G，还是 worker 报这个错误...

如果是用xdl_submit提交的话，系统会给分布式failover预留内存，建议分布式模式下增加一些ps的数量。

**Comment by sosofun** [comment]
> > > ps的内存不够，在配置文件XXX.json里面增加ps的个数，或者增加单个ps的内存。
> > 
> > 
> > 不应该啊， 同样的数据，local就没有问题， 改分布式1ps /1 worker, 把ps 内存从48G增加到128G，还是 worker 报这个错误...
> 
> 如果是用xdl_submit提交的话，系统会给分布式failover预留内存，建议分布式模式下增加一些ps的数量。

哦，哪里配置预留内存大小呢？ 我是把xdl 跑在了k8s上，没用xdl_submit..

**Comment by yiling-dc** [comment]
> > > > ps的内存不够，在配置文件XXX.json里面增加ps的个数，或者增加单个ps的内存。
> > > 
> > > 
> > > 不应该啊， 同样的数据，local就没有问题， 改分布式1ps /1 worker, 把ps 内存从48G增加到128G，还是 worker 报这个错误...
> > 
> > 
> > 如果是用xdl_submit提交的话，系统会给分布式failover预留内存，建议分布式模式下增加一些ps的数量。
> 
> 哦，哪里配置预留内存大小呢？ 我是把xdl 跑在了k8s上，没用xdl_submit..

在training/env.py下有相关代码，另外，local模式没有做Placement，没有真正检查内存是否够用。如果模型较大还是建议用分布式模式，多配一些ps数量。
